# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mathpix-objc-example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mathpix-objc-example
  pod 'AFNetworking', '~> 3.0'
end
